### ISSUE TITLE
Adaptar a RAM

### ISSUE THREAD

**Issue by luccareinehr** [viniciustmoraes/RISC-V-Architecture#5]
Pegar RAM pronta e adaptar para words de 32 bits

**Comment by viniciustmoraes** [comment]
Código de d9fcb8421ce8d4251873a479e8efedec29b333e3 funciona, tendo implementado a RAM para 12 bits de endereço (4096 registros) com palavra de 32 bits. 

Simulações foram feitas para uma RAM menor, com 8 bits de endereçamento. Resultados coerentes de escrita e leitura

![image](https://user-images.githubusercontent.com/108306600/211403200-084f124c-72f5-406f-9d55-ab3bb06cee35.png)
